backend/modules/business/controllers/WorkplacePhotosController.php
<?php

namespace app\modules\business\controllers;

use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Url;
use yii\helpers\Html;
use yii\web\UploadedFile;
use yii\helpers\BaseFileHelper;
use yii\helpers\FileHelper;
use yii\helpers\Json;
use yii\helpers\ArrayHelper;

use yii\imagine;
use yii\imagine\Image;
use Imagine\Image\Box;
use Imagine\Image\Point;
use Imagine\Image\ImageInterface;

//Models
use common\models\Shops;
use common\models\Uploads;

/**
 * ClientsController implements the CRUD actions for Client model.
 */
class WorkplacePhotosController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Client models.
     * @return mixed
     */
    public function actionIndex()
    {
        $this->layout = '@app/themes/pinlist/layouts/main_file_upload';
        $session = Yii::$app->session;
        $clientID = $session['currentclientID'];
        $id = $session['shopID'];
        
        $datas = Uploads::find()->where(['ref'=>$id, 'gallery_type' => 'S'])->all();
        return $this->render('index', [
            'datas'=>$datas,
        ]);
    }
    
    public function actionImages()
    {
        $this->layout = '@app/themes/pinlist/layouts/main_file_upload';
        $session = Yii::$app->session;
        $clientID = $session['currentclientID'];
        $id = $session['shopID'];
        
        $action=Yii::$app->request->post('action');
        if (Yii::$app->request->post()){
            $this->Uploads(false);
            \Yii::$app->getSession()->setFlash('success', 'Success | Successfully saved');
            return $this->redirect(['index']); 
        }else {
            list($initialPreview,$initialPreviewConfig) = $this->getInitialPreview($id);

            return $this->render('update', [
                //'model' => $model,
                'initialPreview'=>$initialPreview,
                    'initialPreviewConfig'=>$initialPreviewConfig,
            ]);
        }
        
        
        //Yii::$app->session->setFlash('success', 'CUSTOM TITLE | noty success');
        //\Yii::$app->getSession()->setFlash('success', 'CUSTOM TITLE | noty success');
        
        
    }
    
    //$this->Uploads(false);
    
    
    /**
     * Finds the Client model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Client the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Shops::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    
    /*|*********************************************************************************|
  |================================ Upload Ajax ====================================|
  |*********************************************************************************|*/
    public function actionUploadajax(){
           $this->Uploads(true);
     }
    private function CreateDir($folderName){
        if($folderName != NULL){
            $basePath = Yii::getAlias('@webroot').'/upload/workplace-photos/';
            //$basePath = VIPProduct::getUploadPath();
            //FileHelper::createDirectory($basePath.$folderName,0777);
            if(FileHelper::createDirectory($basePath.$folderName,0777)){
                FileHelper::createDirectory($basePath.$folderName.'/thumbnail',0777);
            }
        }
        return;
    }
    private function removeUploadDir($dir){
        FileHelper::removeDirectory(VIPProduct::getUploadPath().$dir);
    }
    private function Uploads($isAjax=false) {
        $session = Yii::$app->session;
        $clientID = $session['currentclientID'];
        $ref = $session['shopID'];
        
             if (Yii::$app->request->isPost) {

                $images = UploadedFile::getInstancesByName('upload_ajax');
                if ($images) {
                    /*if($isAjax===true){
                        $ref ='llll';
                    }else{
                        $PhotoLibrary = Yii::$app->request->post('VIPProduct');
                        $ref = $PhotoLibrary['ref'];
                    }*/

                    $this->CreateDir($ref);
                    foreach ($images as $file){
                        $fileName       = $file->baseName . '.' . $file->extension;
                        $realFileName   = md5($file->baseName.time()) . '.' . $file->extension;
                        $savePath       = 'upload/workplace-photos/'.$ref.'/'. $realFileName;
    
                    
                        if($file->saveAs($savePath)){
                            if($this->isImage(Url::base(true).'/'.$savePath)){
                                //var_dump(createThumbnail($ref,$realFileName));
                                $this->createThumbnail($ref,$realFileName);
                            }
                          
                            $model                  = new Uploads;
                            $model->ref             = $ref;
                            $model->gallery_type    = 'S';
                            $model->file_name       = $fileName;
                            $model->real_filename   = $realFileName;
                            $model->save();
                            if($isAjax===true){
                                echo json_encode(['success' => 'true']);
                            }
                            
                        }else{
                            if($isAjax===true){
                                echo json_encode(['success'=>'false','eror'=>$file->error]);
                            }
                        } 
                    }
                }
            }
    }
    private function getInitialPreview($ref) {
            $datas = Uploads::find()->where(['ref'=>$ref, 'gallery_type' => 'S'])->all();
            $initialPreview = [];
            $initialPreviewConfig = [];
            foreach ($datas as $key => $value) {
                array_push($initialPreview, $this->getTemplatePreview($value));
                array_push($initialPreviewConfig, [
                    'caption'=> $value->file_name,
                    'width'  => '120px',
                    'url'    => Url::to(['/business/workplace-photos/deletefile-ajax']),
                    'key'    => $value->upload_id
                ]);
            }
            return  [$initialPreview,$initialPreviewConfig];
    }
    public function isImage($filePath){
            return @is_array(getimagesize($filePath)) ? true : false;
    }
    private function getTemplatePreview(Uploads $model){     
            //$filePath = VIPProduct::getUploadUrl().$model->ref.'/thumbnail/'.$model->real_filename;
            $filePath = Url::base(true).'/upload/workplace-photos/'.$model->ref.'/thumbnail/'.$model->real_filename;
            $isImage  = $this->isImage($filePath);
            if($isImage){
                $file = Html::img($filePath,['class'=>'file-preview-image', 'alt'=>$model->file_name, 'title'=>$model->file_name]);
            }else{
                $file =  "<div class='file-preview-other'> " .
                         "<h2><i class='glyphicon glyphicon-file'></i></h2>" .
                         "</div>";
            }
            return $file;
    }
    private function createThumbnail($folderName,$fileName,$width=270){
      $uploadPath   = Yii::getAlias('@webroot').'/'.'upload/workplace-photos/'.$folderName.'/'; 
      $file         = $uploadPath.$fileName;
      $image        = Yii::$app->image->load($file);
      $image->resize($width);
      $image->save($uploadPath.'thumbnail/'.$fileName);
      return;
    }
    
    public function actionDeletefileAjax(){
        $this->enableCsrfValidation = false;
        $model = Uploads::findOne(Yii::$app->request->post('key'));
        
        if($model!==NULL){
            $filename  = 'upload/workplace-photos/'.$model->ref.'/'.$model->real_filename;
            $thumbnail = 'upload/workplace-photos/'.$model->ref.'/thumbnail/'.$model->real_filename;
            if($model->delete()){
                @unlink($filename);
                @unlink($thumbnail);
                echo json_encode(['success'=>true]);
            }else{
                print_r($model->getErrors());
                echo json_encode(['success'=>false]);
            }
        }else{
          echo json_encode(['success'=>false]);  
        }
    }
}

backend/modules/business/views/workplace-photos/_form.php
<?php

use yii\helpers\Html;
//use yii\widgets\ActiveForm;
use kartik\widgets\FileInput;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model common\models\Client */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="client-form">

<?=Html::beginForm(['workplace-photos/images'],'post',['enctype' => 'multipart/form-data']);?>
    <div class="row form-group">
        <div class="col-lg-12">
            <?php
            echo FileInput::widget([
    'name' => 'upload_ajax[]',
    'options'=>[
        'multiple'=>true
    ],
    'pluginOptions' => [
        'showUpload' => false,
        'showRemove' => false,
        'showCancel' => false,
        'overwriteInitial' => false,
        'initialPreviewShowDelete' => true,        
        'allowedFileExtensions' => ['jpg', 'png', 'jpeg', 'bmp', 'tiff'],
        'initialPreview' => $initialPreview,
        //'initialPreview'=> $initialPreview[$model->ref],
        //'initialPreviewConfig'=>$model->initialPreview($model->docs,'docs','config'),
        'initialPreviewConfig' => $initialPreviewConfig,
        'uploadUrl' => Url::to(['/business/workplace-photos/uploadajax']),
        'uploadAsync' => false,
        'maxFileCount' => 4
    ]
]);
            ?>

        </div>
        
    </div>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success btn-block','method' => 'post',]) ?>
    </div>
<?= Html::endForm();?> 
</div>

backend/modules/business/views/workplace-photos/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model common\models\Client */

$this->title = 'Workplace Photos';
//$this->params['breadcrumbs'][] = ['label' => 'Clients', 'url' => ['index']];
//$this->params['breadcrumbs'][] = ['label' => $model->company_name, 'url' => ['view', 'id' => $model->client_id]];
//$this->params['breadcrumbs'][] = 'Update';
?>
<div class="col-md-12 col-lg-12 client-update">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title"><?= Html::encode($this->title) ?></h3>
        </div>
        
        <div class="card-body">
            <div class="mail-option">
                               
                <div class="btn-group hidden-phone">
                    <?= Html::a('<i class="fa fa-plus"></i> Add New', ['images'], ['class'=>'btn btn-primary bg-primary text-white']); ?>
                </div>
            </div>
            
            <div class="demo-gallery">
                <?php 
                if(count($datas) > 0) {
                    echo '<ul id="lightgallery" class="list-unstyled row ">';
                    foreach ($datas as $model) {
                        $filePath = Url::base(true).'/upload/workplace-photos/'.$model->ref.'/thumbnail/'.$model->real_filename;
                        $isImage  = @is_array(getimagesize($filePath)) ? true : false;
                        if($isImage){
                            $filePathBig = Url::base(true).'/upload/workplace-photos/'.$model->ref.'/'.$model->real_filename;
                            //$file = Html::img($filePath,['class'=>'file-preview-image', 'alt'=>$model->file_name, 'title'=>$model->file_name]);
                            echo '<li class="col-xs-6 col-sm-4 col-md-3" data-responsive="'.$filePathBig.'" data-src="'.$filePathBig.'" data-sub-html="<h4>Gallery Image 1</h4>" >
                                <a href="">
                                    <img class="img-responsive" src="'.$filePath.'" alt="Thumb-1">
                                </a>
                            </li>';
                        }
                    }
                    echo '</ul>';
                }
                ?>
            </div>
        </div>
    </div>
</div>

backend/modules/business/views/workplace-photos/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Client */

$this->title = 'Salon Info';
//$this->params['breadcrumbs'][] = ['label' => 'Clients', 'url' => ['index']];
//$this->params['breadcrumbs'][] = ['label' => $model->company_name, 'url' => ['view', 'id' => $model->client_id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="col-md-12 col-lg-12 client-update">
    <div class="card">
        <div class="card-header">
            <div class="card-title"><?= Html::encode($this->title) ?></div>
        </div>
        <div class="card-body mb-0">
            <?= $this->render('_form', [
                //'model' => $model,
                'initialPreview'=>$initialPreview,
                'initialPreviewConfig'=>$initialPreviewConfig,
            ]) ?>
        </div>
    </div>
</div>